PP-4644 - Android complaining about missing object that docs said we shouldnt include
Google state here that the transactionInfo object is required —  https://developers.google.com/pay/api/web/guides/tutorial#paymentdatarequest
But here they say it isnt https://developers.google.com/pay/api/web/guides/paymentrequest/tutorial#parameter-reference

Whilst testing on an Android device we got this error
> WalletMerchantError: Error in loadWebPaymentData: PaymentDataRequest.transactionInfo is required!

So we’re adding it anyway to see if this fixes it, it doesn’t break it
on Chrome on desktop